apiVersion: v1
kind: Service
metadata:
  name: client-react-nginx
  labels:
    {{- include "client-react.labels" . | nindent 4 }}
spec:
  selector:
    app: client-react-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
