# ⛔️ DONT PUT SECRET FILES IN VCS -- carried over from the course as-is.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.superuser.secretName }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.superuser.username | quote }}
  user: {{ .Values.superuser.username | quote }}
  password: {{ .Values.superuser.password | quote }}
