# ⛔️ DONT PUT SECRET FILES IN VCS -- carried over from the course as-is.
apiVersion: v1
kind: Secret
metadata:
  name: api-node-database-url
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
