replicaCount: 3

image:
  tag: 1.4.1 # production_services/go/api-golang

dbMigrator:
  image:
    tag: 1.4.1 # production_services/other/api-golang-migrator

ingress:
  host: gha-course.devopsdirective.com
