apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-golang
  labels:
    {{- include "api-golang.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-golang
  template:
    metadata:
      labels:
        app: api-golang
    spec:
      containers:
        - name: api-golang
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.containerPort | quote }}
          envFrom:
            - secretRef:
                name: api-golang-database-url
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
