# ⛔️ DONT PUT SECRET FILES IN VCS -- carried over from the course as-is.
apiVersion: v1
kind: Secret
metadata:
  name: api-golang-database-url
type: Opaque
stringData:
  DATABASE_URL: {{ include "api-golang.databaseUrl" . | quote }}
