apiVersion: v1
kind: Service
metadata:
  name: api-golang
  labels:
    {{- include "api-golang.labels" . | nindent 4 }}
spec:
  selector:
    app: api-golang
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
